hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - num_clients=10
    - num_rounds=100
    - batch_size=32
    - iid=True
    - client_fraction=1.0
    - frac_eval=1.0
    - fed_optimizer=FedAdagrad,FedAdam,FedYogi,FedProx,FedAvgM,FedAvg
    - current_test=fed_optimizer
    - learning_rate=0.1
  job:
    name: main
    chdir: null
    override_dirname: batch_size=32,client_fraction=1.0,current_test=fed_optimizer,fed_optimizer=FedAdagrad,FedAdam,FedYogi,FedProx,FedAvgM,FedAvg,frac_eval=1.0,iid=True,learning_rate=0.1,num_clients=10,num_rounds=100
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /datadrive/storage_folder/daniel/flower_dolander1/baselines/flwr_baselines/publications/fedavg_mnist
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /datadrive/storage_folder/daniel/flower_dolander1/baselines/flwr_baselines/publications/fedavg_mnist/docs/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
num_clients: 10
num_rounds: 100
num_epochs: 1
batch_size: 32
iid: true
balance: true
client_fraction: 1.0
expected_maximum: 0.9924
learning_rate: 0.1
frac_eval: 1.0
mu: 1.0
save_path: docs/tmpResults
fed_optimizer: FedAvg
current_test: fed_optimizer
eta: 0.1
eta1: 0.1
tau: 0.01
get_initial_parameters:
  _target_: utils.get_initial_parameters
